In [ ]:
import pandas as pd

sales = pd.read_csv('/content/sample_sales_data.csv')
print(sales)

    OrderID CustomerName     Category  OrderDate  Quantity   Price  \
0   ORD0001       Hannah        Books   1/1/2025         6  331.73
1   ORD0002       Edward        Books   1/2/2025         3  310.03
2   ORD0003        Alice     Clothing   1/3/2025         9  176.17
3   ORD0004       Hannah  Electronics   1/4/2025         3   79.97
4   ORD0005       George         Home   1/5/2025         7  406.03
..      ...          ...          ...        ...       ...     ...
95  ORD0096        Diana     Clothing   4/6/2025         5  368.23
96  ORD0097          Bob        Books   4/7/2025         8  360.17
97  ORD0098        Diana     Clothing   4/8/2025         9   29.97
98  ORD0099        Alice         Home   4/9/2025         5  465.20
99  ORD0100      Charlie        Books  4/10/2025         9   41.55

    TotalAmount     Status
0       1990.38   Canceled
1        930.09  Completed
2       1585.53   Canceled
3        239.91    Pending
4       2842.21   Canceled
..          ...        ...
95      1841.15  Completed
96      2881.36  Completed
97       269.73   Canceled
98      2326.00    Pending
99       373.95    Pending

[100 rows x 8 columns]

In [ ]:
sales[sales['TotalAmount'] > 500]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
0,ORD0001,Hannah,Books,1/1/2025,6,331.73,1990.38,Canceled
1,ORD0002,Edward,Books,1/2/2025,3,310.03,930.09,Completed
2,ORD0003,Alice,Clothing,1/3/2025,9,176.17,1585.53,Canceled
4,ORD0005,George,Home,1/5/2025,7,406.03,2842.21,Canceled
5,ORD0006,Charlie,Books,1/6/2025,9,390.27,3512.43,Completed
...,...,...,...,...,...,...,...,...
92,ORD0093,Charlie,Electronics,4/3/2025,5,118.72,593.60,Completed
94,ORD0095,Alice,Books,4/5/2025,4,143.94,575.76,Canceled
95,ORD0096,Diana,Clothing,4/6/2025,5,368.23,1841.15,Completed
96,ORD0097,Bob,Books,4/7/2025,8,360.17,2881.36,Completed
98,ORD0099,Alice,Home,4/9/2025,5,465.20,2326.00,Pending

In [ ]:
sales[sales['Category'] == 'Electronics']

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
3,ORD0004,Hannah,Electronics,1/4/2025,3,79.97,239.91,Pending
8,ORD0009,Charlie,Electronics,1/9/2025,2,222.30,444.60,Canceled
10,ORD0011,Edward,Electronics,1/11/2025,3,398.62,1195.86,Canceled
20,ORD0021,Charlie,Electronics,1/21/2025,8,358.75,2870.00,Pending
22,ORD0023,Hannah,Electronics,1/23/2025,8,134.65,1077.20,Completed
35,ORD0036,Edward,Electronics,2/5/2025,4,340.00,1360.00,Canceled
41,ORD0042,Diana,Electronics,2/11/2025,9,214.39,1929.51,Pending
46,ORD0047,Hannah,Electronics,2/16/2025,9,54.83,493.47,Pending
49,ORD0050,Edward,Electronics,2/19/2025,9,203.61,1832.49,Canceled
51,ORD0052,Fiona,Electronics,2/21/2025,2,55.77,111.54,Canceled
57,ORD0058,Diana,Electronics,2/27/2025,10,161.56,1615.60,Canceled
62,ORD0063,Fiona,Electronics,3/4/2025,8,485.02,3880.16,Pending
69,ORD0070,Bob,Electronics,3/11/2025,1,264.61,264.61,Canceled
70,ORD0071,Diana,Electronics,3/12/2025,7,305.67,2139.69,Completed
73,ORD0074,NaN,Electronics,3/15/2025,1,234.80,234.80,Pending
74,ORD0075,Charlie,Electronics,3/16/2025,3,235.91,707.73,Completed
80,ORD0081,Hannah,Electronics,NaN,1,295.33,295.33,Canceled
85,ORD0086,Bob,Electronics,NaN,5,77.85,389.25,Pending
86,ORD0087,Alice,Electronics,3/28/2025,3,86.55,259.65,Pending
87,ORD0088,Charlie,Electronics,3/29/2025,5,218.10,1090.50,Canceled
90,ORD0091,Edward,Electronics,4/1/2025,9,111.69,1005.21,Pending
92,ORD0093,Charlie,Electronics,4/3/2025,5,118.72,593.60,Completed
93,ORD0094,Alice,Electronics,4/4/2025,2,60.11,120.22,Canceled

In [ ]:
sales[(sales['Category'] == "Clothing") & (sales['Status'] == 'Completed')]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
17,ORD0018,George,Clothing,1/18/2025,10,267.14,2671.40,Completed
18,ORD0019,Alice,Clothing,NaN,3,227.82,683.46,Completed
23,ORD0024,Bob,Clothing,1/24/2025,5,293.58,1467.90,Completed
26,ORD0027,Charlie,Clothing,1/27/2025,3,432.17,1296.51,Completed
54,ORD0055,Bob,Clothing,2/24/2025,9,142.33,1280.97,Completed
58,ORD0059,Fiona,Clothing,2/28/2025,7,161.67,1131.69,Completed
66,ORD0067,Diana,Clothing,3/8/2025,3,467.02,1401.06,Completed
76,ORD0077,Alice,Clothing,3/18/2025,9,163.71,1473.39,Completed
77,ORD0078,Alice,Clothing,3/19/2025,2,25.33,50.66,Completed
78,ORD0079,NaN,Clothing,3/20/2025,6,80.48,482.88,Completed
95,ORD0096,Diana,Clothing,4/6/2025,5,368.23,1841.15,Completed

In [ ]:
sales[(sales['Quantity'] > 5) | (sales['Status'] == 'Pending')]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
0,ORD0001,Hannah,Books,1/1/2025,6,331.73,1990.38,Canceled
2,ORD0003,Alice,Clothing,1/3/2025,9,176.17,1585.53,Canceled
3,ORD0004,Hannah,Electronics,1/4/2025,3,79.97,239.91,Pending
4,ORD0005,George,Home,1/5/2025,7,406.03,2842.21,Canceled
5,ORD0006,Charlie,Books,1/6/2025,9,390.27,3512.43,Completed
...,...,...,...,...,...,...,...,...
91,ORD0092,Diana,Clothing,4/2/2025,2,172.55,345.10,Pending
96,ORD0097,Bob,Books,4/7/2025,8,360.17,2881.36,Completed
97,ORD0098,Diana,Clothing,4/8/2025,9,29.97,269.73,Canceled
98,ORD0099,Alice,Home,4/9/2025,5,465.20,2326.00,Pending
99,ORD0100,Charlie,Books,4/10/2025,9,41.55,373.95,Pending

In [ ]:
sales[sales['TotalAmount'].between(200,1000)]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
1,ORD0002,Edward,Books,1/2/2025,3,310.03,930.09,Completed
3,ORD0004,Hannah,Electronics,1/4/2025,3,79.97,239.91,Pending
8,ORD0009,Charlie,Electronics,1/9/2025,2,222.30,444.60,Canceled
11,ORD0012,Alice,Home,1/12/2025,4,157.95,631.80,Completed
12,ORD0013,Fiona,Clothing,1/13/2025,9,44.52,400.68,Pending
13,ORD0014,Charlie,Home,1/14/2025,2,108.11,216.22,Completed
15,ORD0016,Hannah,Clothing,1/16/2025,1,241.91,241.91,Pending
18,ORD0019,Alice,Clothing,NaN,3,227.82,683.46,Completed
19,ORD0020,George,Clothing,1/20/2025,2,462.31,924.62,Canceled
21,ORD0022,Fiona,Home,1/22/2025,9,62.70,564.30,Pending
31,ORD0032,Bob,Books,2/1/2025,6,149.55,897.30,Completed
37,ORD0038,Hannah,Home,2/7/2025,6,135.51,813.06,Canceled
40,ORD0041,George,Clothing,2/10/2025,5,123.01,615.05,Pending
42,ORD0043,Alice,Clothing,2/12/2025,9,92.59,833.31,Pending
45,ORD0046,George,Home,2/15/2025,2,119.26,238.52,Completed
46,ORD0047,Hannah,Electronics,2/16/2025,9,54.83,493.47,Pending
48,ORD0049,Bob,Clothing,2/18/2025,3,147.93,443.79,Canceled
52,ORD0053,Edward,Home,2/22/2025,2,261.63,523.26,Pending
55,ORD0056,Alice,Clothing,2/25/2025,6,161.37,968.22,Pending
65,ORD0066,NaN,Clothing,3/7/2025,5,190.90,954.50,Pending
69,ORD0070,Bob,Electronics,3/11/2025,1,264.61,264.61,Canceled
71,ORD0072,Fiona,Home,3/13/2025,3,204.01,612.03,Completed
73,ORD0074,NaN,Electronics,3/15/2025,1,234.80,234.80,Pending
74,ORD0075,Charlie,Electronics,3/16/2025,3,235.91,707.73,Completed
75,ORD0076,Edward,Books,3/17/2025,1,360.33,360.33,Canceled
78,ORD0079,NaN,Clothing,3/20/2025,6,80.48,482.88,Completed
80,ORD0081,Hannah,Electronics,NaN,1,295.33,295.33,Canceled
85,ORD0086,Bob,Electronics,NaN,5,77.85,389.25,Pending
86,ORD0087,Alice,Electronics,3/28/2025,3,86.55,259.65,Pending
89,ORD0090,Alice,Books,3/31/2025,1,215.99,215.99,Canceled
91,ORD0092,Diana,Clothing,4/2/2025,2,172.55,345.10,Pending
92,ORD0093,Charlie,Electronics,4/3/2025,5,118.72,593.60,Completed
94,ORD0095,Alice,Books,4/5/2025,4,143.94,575.76,Canceled
97,ORD0098,Diana,Clothing,4/8/2025,9,29.97,269.73,Canceled
99,ORD0100,Charlie,Books,4/10/2025,9,41.55,373.95,Pending

In [ ]:
sales[sales['CustomerName'].str.startswith('A', na = False)]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
2,ORD0003,Alice,Clothing,1/3/2025,9,176.17,1585.53,Canceled
9,ORD0010,Alice,Home,1/10/2025,3,476.14,1428.42,Pending
11,ORD0012,Alice,Home,1/12/2025,4,157.95,631.80,Completed
18,ORD0019,Alice,Clothing,NaN,3,227.82,683.46,Completed
42,ORD0043,Alice,Clothing,2/12/2025,9,92.59,833.31,Pending
55,ORD0056,Alice,Clothing,2/25/2025,6,161.37,968.22,Pending
64,ORD0065,Alice,Books,3/6/2025,5,469.38,2346.90,Completed
76,ORD0077,Alice,Clothing,3/18/2025,9,163.71,1473.39,Completed
77,ORD0078,Alice,Clothing,3/19/2025,2,25.33,50.66,Completed
79,ORD0080,Alice,Clothing,3/21/2025,6,244.66,1467.96,Pending
81,ORD0082,Alice,Home,3/23/2025,3,346.71,1040.13,Pending
84,ORD0085,Alice,Home,3/26/2025,1,124.89,124.89,Canceled
86,ORD0087,Alice,Electronics,3/28/2025,3,86.55,259.65,Pending
89,ORD0090,Alice,Books,3/31/2025,1,215.99,215.99,Canceled
93,ORD0094,Alice,Electronics,4/4/2025,2,60.11,120.22,Canceled
94,ORD0095,Alice,Books,4/5/2025,4,143.94,575.76,Canceled
98,ORD0099,Alice,Home,4/9/2025,5,465.20,2326.00,Pending

In [ ]:
sales[sales['Category'].str.contains('Home')]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
4,ORD0005,George,Home,1/5/2025,7,406.03,2842.21,Canceled
9,ORD0010,Alice,Home,1/10/2025,3,476.14,1428.42,Pending
11,ORD0012,Alice,Home,1/12/2025,4,157.95,631.80,Completed
13,ORD0014,Charlie,Home,1/14/2025,2,108.11,216.22,Completed
14,ORD0015,Charlie,Home,1/15/2025,10,381.90,3819.00,Canceled
21,ORD0022,Fiona,Home,1/22/2025,9,62.70,564.30,Pending
24,ORD0025,Edward,Home,1/25/2025,10,262.13,2621.30,Canceled
25,ORD0026,Charlie,Home,1/26/2025,4,318.66,1274.64,Pending
30,ORD0031,Diana,Home,1/31/2025,2,61.32,122.64,Completed
32,ORD0033,Hannah,Home,2/2/2025,4,263.42,1053.68,Canceled
37,ORD0038,Hannah,Home,2/7/2025,6,135.51,813.06,Canceled
44,ORD0045,Hannah,Home,2/14/2025,6,418.15,2508.90,Pending
45,ORD0046,George,Home,2/15/2025,2,119.26,238.52,Completed
47,ORD0048,Hannah,Home,NaN,8,23.50,188.00,Pending
50,ORD0051,Edward,Home,2/20/2025,5,276.70,1383.50,Completed
52,ORD0053,Edward,Home,2/22/2025,2,261.63,523.26,Pending
53,ORD0054,Bob,Home,2/23/2025,5,465.84,2329.20,Completed
63,ORD0064,Bob,Home,3/5/2025,5,367.43,1837.15,Completed
68,ORD0069,Edward,Home,3/10/2025,6,201.93,1211.58,Pending
71,ORD0072,Fiona,Home,3/13/2025,3,204.01,612.03,Completed
72,ORD0073,Hannah,Home,3/14/2025,9,203.84,1834.56,Canceled
81,ORD0082,Alice,Home,3/23/2025,3,346.71,1040.13,Pending
84,ORD0085,Alice,Home,3/26/2025,1,124.89,124.89,Canceled
98,ORD0099,Alice,Home,4/9/2025,5,465.20,2326.00,Pending

In [ ]:
sales[sales['CustomerName'].isnull()]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
65,ORD0066,NaN,Clothing,3/7/2025,5,190.90,954.50,Pending
67,ORD0068,NaN,Books,3/9/2025,8,144.79,1158.32,Canceled
73,ORD0074,NaN,Electronics,3/15/2025,1,234.80,234.80,Pending
78,ORD0079,NaN,Clothing,3/20/2025,6,80.48,482.88,Completed
83,ORD0084,NaN,Clothing,NaN,4,278.01,1112.04,Canceled

In [ ]:
sales[sales['OrderDate'].notnull()]

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
0,ORD0001,Hannah,Books,1/1/2025,6,331.73,1990.38,Canceled
1,ORD0002,Edward,Books,1/2/2025,3,310.03,930.09,Completed
2,ORD0003,Alice,Clothing,1/3/2025,9,176.17,1585.53,Canceled
3,ORD0004,Hannah,Electronics,1/4/2025,3,79.97,239.91,Pending
4,ORD0005,George,Home,1/5/2025,7,406.03,2842.21,Canceled
...,...,...,...,...,...,...,...,...
95,ORD0096,Diana,Clothing,4/6/2025,5,368.23,1841.15,Completed
96,ORD0097,Bob,Books,4/7/2025,8,360.17,2881.36,Completed
97,ORD0098,Diana,Clothing,4/8/2025,9,29.97,269.73,Canceled
98,ORD0099,Alice,Home,4/9/2025,5,465.20,2326.00,Pending
99,ORD0100,Charlie,Books,4/10/2025,9,41.55,373.95,Pending

In [ ]:
sales[sales['Status'] == 'Completed']

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
1,ORD0002,Edward,Books,1/2/2025,3,310.03,930.09,Completed
5,ORD0006,Charlie,Books,1/6/2025,9,390.27,3512.43,Completed
6,ORD0007,Bob,Books,1/7/2025,7,154.19,1079.33,Completed
11,ORD0012,Alice,Home,1/12/2025,4,157.95,631.80,Completed
13,ORD0014,Charlie,Home,1/14/2025,2,108.11,216.22,Completed
17,ORD0018,George,Clothing,1/18/2025,10,267.14,2671.40,Completed
18,ORD0019,Alice,Clothing,NaN,3,227.82,683.46,Completed
22,ORD0023,Hannah,Electronics,1/23/2025,8,134.65,1077.20,Completed
23,ORD0024,Bob,Clothing,1/24/2025,5,293.58,1467.90,Completed
26,ORD0027,Charlie,Clothing,1/27/2025,3,432.17,1296.51,Completed
30,ORD0031,Diana,Home,1/31/2025,2,61.32,122.64,Completed
31,ORD0032,Bob,Books,2/1/2025,6,149.55,897.30,Completed
33,ORD0034,Fiona,Books,2/3/2025,9,217.43,1956.87,Completed
45,ORD0046,George,Home,2/15/2025,2,119.26,238.52,Completed
50,ORD0051,Edward,Home,2/20/2025,5,276.70,1383.50,Completed
53,ORD0054,Bob,Home,2/23/2025,5,465.84,2329.20,Completed
54,ORD0055,Bob,Clothing,2/24/2025,9,142.33,1280.97,Completed
56,ORD0057,George,Books,2/26/2025,6,324.40,1946.40,Completed
58,ORD0059,Fiona,Clothing,2/28/2025,7,161.67,1131.69,Completed
60,ORD0061,Bob,Books,3/2/2025,9,336.13,3025.17,Completed
63,ORD0064,Bob,Home,3/5/2025,5,367.43,1837.15,Completed
64,ORD0065,Alice,Books,3/6/2025,5,469.38,2346.90,Completed
66,ORD0067,Diana,Clothing,3/8/2025,3,467.02,1401.06,Completed
70,ORD0071,Diana,Electronics,3/12/2025,7,305.67,2139.69,Completed
71,ORD0072,Fiona,Home,3/13/2025,3,204.01,612.03,Completed
74,ORD0075,Charlie,Electronics,3/16/2025,3,235.91,707.73,Completed
76,ORD0077,Alice,Clothing,3/18/2025,9,163.71,1473.39,Completed
77,ORD0078,Alice,Clothing,3/19/2025,2,25.33,50.66,Completed
78,ORD0079,NaN,Clothing,3/20/2025,6,80.48,482.88,Completed
88,ORD0089,Bob,Books,3/30/2025,9,302.63,2723.67,Completed
92,ORD0093,Charlie,Electronics,4/3/2025,5,118.72,593.60,Completed
95,ORD0096,Diana,Clothing,4/6/2025,5,368.23,1841.15,Completed
96,ORD0097,Bob,Books,4/7/2025,8,360.17,2881.36,Completed

In [ ]:
salescolumns = sales[['OrderID', 'CustomerName', 'TotalAmount']]
salescolumns

    OrderID CustomerName  TotalAmount
0   ORD0001       Hannah      1990.38
1   ORD0002       Edward       930.09
2   ORD0003        Alice      1585.53
3   ORD0004       Hannah       239.91
4   ORD0005       George      2842.21
..      ...          ...          ...
95  ORD0096        Diana      1841.15
96  ORD0097          Bob      2881.36
97  ORD0098        Diana       269.73
98  ORD0099        Alice      2326.00
99  ORD0100      Charlie       373.95

[100 rows x 3 columns]

In [ ]:
mask  = sales['Price'] > 100
mask

0      True
1      True
2      True
3     False
4      True
      ...
95     True
96     True
97    False
98     True
99    False
Name: Price, Length: 100, dtype: bool

In [ ]:
filter = sales[mask]
filter

,OrderID,CustomerName,Category,OrderDate,Quantity,Price,TotalAmount,Status
0,ORD0001,Hannah,Books,1/1/2025,6,331.73,1990.38,Canceled
1,ORD0002,Edward,Books,1/2/2025,3,310.03,930.09,Completed
2,ORD0003,Alice,Clothing,1/3/2025,9,176.17,1585.53,Canceled
4,ORD0005,George,Home,1/5/2025,7,406.03,2842.21,Canceled
5,ORD0006,Charlie,Books,1/6/2025,9,390.27,3512.43,Completed
...,...,...,...,...,...,...,...,...
92,ORD0093,Charlie,Electronics,4/3/2025,5,118.72,593.60,Completed
94,ORD0095,Alice,Books,4/5/2025,4,143.94,575.76,Canceled
95,ORD0096,Diana,Clothing,4/6/2025,5,368.23,1841.15,Completed
96,ORD0097,Bob,Books,4/7/2025,8,360.17,2881.36,Completed
98,ORD0099,Alice,Home,4/9/2025,5,465.20,2326.00,Pending

In [ ]:
filtered = sales.loc[sales['TotalAmount'] > 500, ['OrderID', 'Status']]
print(filtered)

    OrderID     Status
0   ORD0001   Canceled
1   ORD0002  Completed
2   ORD0003   Canceled
4   ORD0005   Canceled
5   ORD0006  Completed
..      ...        ...
92  ORD0093  Completed
94  ORD0095   Canceled
95  ORD0096  Completed
96  ORD0097  Completed
98  ORD0099    Pending

[72 rows x 2 columns]

In [ ]:
sales.iloc[:10][['OrderID', 'TotalAmount']]

   OrderID  TotalAmount
0  ORD0001      1990.38
1  ORD0002       930.09
2  ORD0003      1585.53
3  ORD0004       239.91
4  ORD0005      2842.21
5  ORD0006      3512.43
6  ORD0007      1079.33
7  ORD0008      2668.60
8  ORD0009       444.60
9  ORD0010      1428.42

In [ ]:
sales.drop(columns=['Status'], inplace = True )

In [ ]:
filtered.to_csv("high_value_orders.csv", index=False)